version: '3.1'

services:

  involta_postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - involta
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  involta_pgadmin:
    links:
      - involta_postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /var/lib/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - involta

networks:
  involta:
    driver: bridge
